### PR TITLE
Added support for formatting (1:1 print) raw HTML and HTML blocks.

### PR DESCRIPTION
**Pull request by bwplotka**
cc @saswatamcode

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
Used in https://github.com/bwplotka/mdox/pull/46

**Review by saswatamcode — APPROVED** [review]
Awesome work! 💫

**Comment by karelbilek** [comment]
Totally missed this, sorry, will check this :)

**Comment by karelbilek** [comment]
No brainer, merging

**Pull request merged**
